// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace DataAccess.Models;

public partial class EmpresaContext : DbContext
{
    public EmpresaContext(DbContextOptions<EmpresaContext> options)
        : base(options)
    {
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

public static class DbContextConfiguration
{
    public static IServiceCollection AddEmpresaContext(this IServiceCollection services, string connectionstring)
    {
        services.AddDbContext<EmpresaContext>(options =>
            options.UseSqlServer(connectionstring));
        return services;
    }
}